### ISSUE TITLE
Contact

### ISSUE THREAD

**Issue by marcoperic** [danpush/StreetNet#1]
Hi. I am working on a similar project and I am interested in your usage of Resnet for this problem. Would you mind sending me an email at --- so we can have a chat about this?

**Comment by danpush** [comment]
Sent you an email!

**Comment by marcoperic** [comment]
Hey!

I have tried out your program and it's super cool! I am becoming more acquainted with ML, so projects like these are great learning experiences for me.

I had a few questions about your training process. I see that you used ResNet18 and ResNet50. Did you train from scratch or was this a transfer learning approach? If you did train from scratch, what was your dataset like?

Currently, I am in the process of creating a 100k+ image balanced dataset using StreetView data (as opposed to Pinterest or Google Image photos of locations that some other approaches use). As a result, I think that the number of images and the relevance will help the model's accuracy drastically. I plan to publish my dataset on Kaggle once it's finished. All countries should have at least 1200 images for training.

Do you think this would be sufficient for ResNet18 or ResNet50? I am having thoughts about increasing the dataset size to 2000+ images per country otherwise.

Again, thanks so much for responding! If you'd like to correspond over IM instead, you can find me on Discord: Marco#9840

Kind regards,
Marco
________________________________
